### ISSUE TITLE
Only Read-Only access

### ISSUE THREAD

**Issue by alexcf** [ellneal/homebridge-igenix-air-conditioner#2]
Awesome work by the way! Thanks for putting this together.

Installed fine, however can only read the air con unit from the Home app, I cannot make changes, i.e. turn it on or off. There's a spinning wheel icon when changes are made, but feels like it times out. Any ideas?

**Comment by ellneal** [comment]
I'd guess you don't have the correct IDs etc. in the config file? I think it does some encryption to messages that it sends. Did you manage to intercept the network communication between the Igenix app and tuya's servers?

Might be worth talking to the guys behind [tuyapi](
https://github.com/codetheweb/tuyapi) as they did all the heavy lifting that allowed me to build this integration.

**Comment by alexcf** [comment]
Ah! Thanks, I just re-checked and there's two "localKey" entries, I pulled the incorrect one. Appreciate you writing back!

**Comment by ellneal** [comment]
No worries, glad you got it running 👍
